apiVersion: v1
kind: Pod
metadata:
  name: demo-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role
            operator: In
            values:
            - db
  containers:
  - name: app
    image: nginx
