apiVersion: v1
kind: Pod
metadata:
  name: test-logger

spec:
  containers:
  - name: logger
    image: busybox
    command:
    - sh
    - -c
    - while true; do echo "EFK logging test running"; sleep 5; done