apiVersion: v1
kind: Pod
metadata:
  name: taint-test
  labels:
    app: taint-demo
spec:
  # This toleration allows the pod to be scheduled on nodes with the matching taint
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "infra"
    effect: "NoSchedule"

  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80