apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota           # quota object name
  namespace: dev            # namespace applied
spec:
  hard:
    pods: "5"               # max 5 pods
    requests.cpu: "2"       # total CPU requests ≤ 2 CPU
    requests.memory: 2Gi    # total memory requests ≤ 2 Gi
    limits.cpu: "4"         # total CPU limits ≤ 4 CPU
    limits.memory: 4Gi      # total memory limits ≤ 4 Gi
    services: "2"           # max 2 services
    configmaps: "5"         # max 5 configmaps
    persistentvolumeclaims: "3" # max 3 PVCs
